[package]
name = "unhtml_derive"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
scraper = "0.8.1"
syn = "0.15.22"
quote = "0.6.10"
proc-macro2 = "0.4.24"
synstructure = "0.10.1"
unhtml = { path = "../unhtml" }