[package]
name = "unhtml"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
license-file = "../LICENSE"
description = "deserializor from html"
repository = "https://github.com/Hexilee/unhtml.rs"
keywords = ["unhtml", "html", "deserializor"]
categories = ["encoding"]

[dependencies]
scraper = "0.8.1"
failure = "0.1.3"
failure_derive = "0.1.3"