[package]
name = "unhtml"
version = "0.7.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
description = "deserializor from html"
repository = "https://github.com/Hexilee/unhtml.rs"
keywords = ["unhtml", "html", "deserializor"]
categories = ["encoding"]
readme = "README.md"
documentation = "https://docs.rs/unhtml"

[dependencies]
scraper = "0.10"
ego-tree = "0.6"
failure = "0.1.3"
failure_derive = "0.1.3"

[badges]
travis-ci = { repository = "Hexilee/unhtml.rs", branch = "master" }