[package]
name = "unhtml"
version = "0.7.1"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A magic html parser"
repository = "https://github.com/Hexilee/unhtml.rs"
keywords = ["unhtml", "html", "parser"]
categories = ["parser-implementations", "web-programming", "encoding"]
readme = "README.md"
documentation = "https://docs.rs/unhtml"

[dependencies]
scraper = "0.10"
ego-tree = "0.6"
failure = "0.1.3"
failure_derive = "0.1.3"
unhtml_derive = { path = "../unhtml_derive", version = "0.7", optional = true }

[features]
derive = ["unhtml_derive"]

[badges]
travis-ci = { repository = "Hexilee/unhtml.rs", branch = "master" }
